From url to path; second batch of fixes
simobasso/djangogirls_revamped pull request #29
Opened 2019-03-06 20:27 UTC by valentinogagliardi

### Descrizione

Il cambiamento più importante in questa PR è il passaggio da `url` a `path`. La funzione `path` è stata introdotta su [Django 2.0](https://docs.djangoproject.com/en/2.1/releases/2.0/#simplified-url-routing-syntax) e semplifica molto il ragionamento attorno agli URL. Credo sia anche molto più semplice comprendere `path` rispetto alla complessità delle espressioni regolari. Oltre a questo la PR sistema alcuni piccoli errori di forma/grammaticali.

### Perchè?

Eliminare le Regex dal tutorial rende meno brutale l'impatto per le persone meno esperte. La PR migliora la forma di alcune frasi; elimina alcuni typo.

2019-03-07 19:56 UTC, yakky commented
@valentinogagliardi grazie mille, much deserved
Faccio una review nel fine settimana perché è un'area delicata 
Davvero ottimo lavoro comunque!

2019-03-15 17:09 UTC, yakky commented on html/README.md
> +### Fai committ e pubblica il tuo codice su Heroku
:heart:

2019-03-15 17:14 UTC, yakky requested changes
Qualche piccolo typo.
Potrebbe essere necessario ribasarla per alcune modifiche intervenute nel frattempo, spuò anche controllare domani perché a questo punto la userei per il prox tutorial

2019-03-15 17:14 UTC, yakky commented on django_orm/README.md
> +Uno dei vantaggi dei QuerySet consiste nell'abilità di filtrarli. Diciamo che vogliamo trovare tutti i post che hanno come autore l'uUtente 'ola'. Possiamo usare `filter` invece di `all` in `Post.obj
`uUtente` -> `utente`

2019-03-15 17:14 UTC, yakky commented on django_urls/README.md
> +Come vedi stiamo assegnando una `view` denominata `post_list` alla URL `''`. Questo schema dirà a Django che `views.post_list` è il posto giusto dove andare se qualcuno entra nel tuo sito all'indiriz
URL non è maschile? :thinking:

2019-03-15 17:14 UTC, yakky commented on dynamic_data_in_templates/README.md
> +Il nostro file `blog/views.py` sara così:
`sarà`

2019-03-15 17:14 UTC, yakky commented on template_extending/README.md
> +Un'altra cosa bella di Django è l'**estensione deil template**. Cosa significa? Significa che puoi usare le stesse parti del tuo HTML per pagine diverse del sito.
`deil` -> `dei` o `del`?

2019-03-16 07:37 UTC, valentinogagliardi commented on template_extending/README.md
> +Un'altra cosa bella di Django è l'**estensione deil template**. Cosa significa? Significa che puoi usare le stesse parti del tuo HTML per pagine diverse del sito.
Tutti errori di distrazione :-)

2019-03-16 09:04 UTC, yakky commented on template_extending/README.md
> +Un'altra cosa bella di Django è l'**estensione deil template**. Cosa significa? Significa che puoi usare le stesse parti del tuo HTML per pagine diverse del sito.
sono un rompi, lo so! Perdono! :bowing_man:

2019-03-16 09:05 UTC, yakky approved these changes

2019-03-16 09:05 UTC, yakky commented
@valentinogagliardi grazie :100:  Aspetto a fare il merge altrimenti gli cambiamo URL in tempo reale :D

2019-04-28 15:49 UTC, yakky approved these changes

2019-04-28 15:50 UTC, merged